In [1]:
import numpy as np

In [51]:
j=[4,6,2,8,9,7]

In [53]:
j

[4, 6, 2, 8, 9, 7]

In [55]:
np.array(j)

array([4, 6, 2, 8, 9, 7])

In [57]:
tuple(j)

(4, 6, 2, 8, 9, 7)

In [59]:
j=[4,6,2,8,9,7]
j


[4, 6, 2, 8, 9, 7]

In [61]:
d=np.array(j)
d


array([4, 6, 2, 8, 9, 7])

In [63]:
type(d)

numpy.ndarray

In [65]:
tuple(j)

(4, 6, 2, 8, 9, 7)

In [67]:
d

array([4, 6, 2, 8, 9, 7])

In [69]:
d.shape

(6,)

In [71]:
d.ndim

1

In [73]:
d.size

6

In [75]:
d.reshape(5,2)

ValueError: cannot reshape array of size 6 into shape (5,2)

In [77]:
h=d.reshape(2,3)
h


array([[4, 6, 2],
       [8, 9, 7]])

In [79]:
h.shape

(2, 3)

In [81]:
h.ndim

2

In [31]:
s=([4, 6, 2, 8, 9],
[4, 6, 3, 8, 9],
[4, 6, 7, 8, 9],
[4, 6, 1, 8, 9])
s






([4, 6, 2, 8, 9], [4, 6, 3, 8, 9], [4, 6, 7, 8, 9], [4, 6, 1, 8, 9])

In [33]:
arr1=np.array(s)
arr1


array([[4, 6, 2, 8, 9],
       [4, 6, 3, 8, 9],
       [4, 6, 7, 8, 9],
       [4, 6, 1, 8, 9]])

In [41]:
arr1.size

20

In [43]:
arr1.shape

(4, 5)

In [45]:
arr1.ndim

2

In [83]:
arr1

array([[4, 6, 2, 8, 9],
       [4, 6, 3, 8, 9],
       [4, 6, 7, 8, 9],
       [4, 6, 1, 8, 9]])

In [85]:
y=arr1.reshape(20,)
y


array([4, 6, 2, 8, 9, 4, 6, 3, 8, 9, 4, 6, 7, 8, 9, 4, 6, 1, 8, 9])

In [87]:
y.ndim

1

In [89]:
y.shape

(20,)

In [91]:
z=arr1.reshape(1,20)
z


array([[4, 6, 2, 8, 9, 4, 6, 3, 8, 9, 4, 6, 7, 8, 9, 4, 6, 1, 8, 9]])

In [93]:
j=[5,87,23,46,62,84,80,45,77,33,80]
j

[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]

In [101]:
range(len(j))

range(0, 11)

In [97]:
y=[]
x=[]
for i in range (len(j)):
    if i%2==0:
       x.append(j[i])
    else:
       y.append(j[i])

In [99]:
for i in j:
    print(j)


[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
