In [1]:
import numpy as np

In [51]:
j=[4,6,2,8,9,7]

In [53]:
j

[4, 6, 2, 8, 9, 7]

In [55]:
np.array(j)

array([4, 6, 2, 8, 9, 7])

In [57]:
tuple(j)

(4, 6, 2, 8, 9, 7)

In [59]:
j=[4,6,2,8,9,7]
j


[4, 6, 2, 8, 9, 7]

In [61]:
d=np.array(j)
d


array([4, 6, 2, 8, 9, 7])

In [63]:
type(d)

numpy.ndarray

In [65]:
tuple(j)

(4, 6, 2, 8, 9, 7)

In [67]:
d

array([4, 6, 2, 8, 9, 7])

In [69]:
d.shape

(6,)

In [71]:
d.ndim

1

In [73]:
d.size

6

In [75]:
d.reshape(5,2)

ValueError: cannot reshape array of size 6 into shape (5,2)

In [77]:
h=d.reshape(2,3)
h


array([[4, 6, 2],
       [8, 9, 7]])

In [79]:
h.shape

(2, 3)

In [81]:
h.ndim

2

In [31]:
s=([4, 6, 2, 8, 9],
[4, 6, 3, 8, 9],
[4, 6, 7, 8, 9],
[4, 6, 1, 8, 9])
s






([4, 6, 2, 8, 9], [4, 6, 3, 8, 9], [4, 6, 7, 8, 9], [4, 6, 1, 8, 9])

In [33]:
arr1=np.array(s)
arr1


array([[4, 6, 2, 8, 9],
       [4, 6, 3, 8, 9],
       [4, 6, 7, 8, 9],
       [4, 6, 1, 8, 9]])

In [41]:
arr1.size

20

In [43]:
arr1.shape

(4, 5)

In [45]:
arr1.ndim

2

In [83]:
arr1

array([[4, 6, 2, 8, 9],
       [4, 6, 3, 8, 9],
       [4, 6, 7, 8, 9],
       [4, 6, 1, 8, 9]])

In [85]:
y=arr1.reshape(20,)
y


array([4, 6, 2, 8, 9, 4, 6, 3, 8, 9, 4, 6, 7, 8, 9, 4, 6, 1, 8, 9])

In [87]:
y.ndim

1

In [89]:
y.shape

(20,)

In [91]:
z=arr1.reshape(1,20)
z


array([[4, 6, 2, 8, 9, 4, 6, 3, 8, 9, 4, 6, 7, 8, 9, 4, 6, 1, 8, 9]])

In [93]:
j=[5,87,23,46,62,84,80,45,77,33,80]
j

[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]

In [101]:
range(len(j))

range(0, 11)

In [97]:
y=[]
x=[]
for i in range (len(j)):
    if i%2==0:
       x.append(j[i])
    else:
       y.append(j[i])

In [99]:
for i in j:
    print(j)


[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]
[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]


In [1]:
stud_2nd=[18,19,20,17,18,18,18,19,19,20,20,20,17,17]

In [3]:
import numpy as np
np.random.randint(18,20,(59))

array([19, 19, 18, 19, 18, 18, 18, 18, 19, 19, 19, 18, 19, 19, 18, 18, 19,
       18, 19, 19, 18, 18, 18, 19, 18, 18, 19, 19, 19, 18, 19, 18, 19, 19,
       18, 18, 18, 18, 19, 19, 19, 19, 19, 18, 18, 19, 19, 18, 18, 19, 18,
       19, 19, 19, 18, 18, 19, 19, 18])

In [5]:
import numpy as np
tenth_std=np.random.randint(15,18,(1000))
tenth_std

array([16, 16, 16, 16, 16, 15, 16, 16, 15, 15, 16, 15, 16, 16, 15, 15, 16,
       15, 16, 16, 16, 17, 17, 15, 16, 17, 17, 15, 15, 17, 15, 15, 17, 15,
       16, 17, 15, 16, 16, 17, 16, 16, 16, 15, 15, 16, 17, 16, 17, 17, 17,
       17, 17, 17, 17, 15, 16, 15, 17, 17, 16, 17, 15, 16, 17, 17, 15, 16,
       17, 17, 17, 16, 15, 15, 15, 16, 16, 17, 17, 15, 15, 16, 15, 17, 16,
       17, 15, 16, 17, 16, 17, 17, 16, 17, 15, 17, 16, 15, 15, 17, 16, 15,
       16, 15, 15, 17, 17, 17, 16, 15, 15, 17, 15, 15, 17, 16, 15, 16, 16,
       17, 15, 16, 15, 16, 16, 16, 15, 15, 17, 16, 17, 17, 17, 16, 15, 15,
       16, 16, 16, 16, 15, 15, 15, 17, 16, 16, 16, 15, 16, 15, 16, 16, 15,
       17, 15, 17, 16, 16, 16, 17, 17, 17, 15, 17, 17, 15, 17, 17, 16, 16,
       15, 15, 16, 15, 16, 16, 16, 17, 17, 17, 15, 16, 16, 15, 16, 17, 16,
       15, 15, 16, 15, 15, 16, 16, 17, 17, 16, 15, 15, 17, 16, 15, 15, 15,
       17, 15, 17, 15, 17, 17, 16, 16, 15, 17, 16, 15, 16, 17, 16, 15, 15,
       16, 15, 16, 15, 16

In [7]:
import numpy as np
tenth_std=np.random.randint(15,18,(1000))
tenth_std+0.5

array([17.5, 15.5, 17.5, 15.5, 16.5, 15.5, 16.5, 16.5, 16.5, 17.5, 15.5,
       17.5, 16.5, 15.5, 17.5, 15.5, 15.5, 15.5, 17.5, 17.5, 17.5, 16.5,
       17.5, 17.5, 16.5, 17.5, 17.5, 16.5, 16.5, 17.5, 15.5, 17.5, 16.5,
       15.5, 16.5, 16.5, 15.5, 15.5, 16.5, 15.5, 15.5, 16.5, 15.5, 17.5,
       16.5, 16.5, 15.5, 16.5, 15.5, 17.5, 15.5, 15.5, 15.5, 16.5, 15.5,
       16.5, 15.5, 17.5, 15.5, 16.5, 16.5, 15.5, 15.5, 15.5, 16.5, 16.5,
       15.5, 15.5, 17.5, 15.5, 15.5, 15.5, 16.5, 15.5, 17.5, 15.5, 16.5,
       17.5, 15.5, 17.5, 15.5, 17.5, 17.5, 17.5, 17.5, 16.5, 15.5, 17.5,
       17.5, 15.5, 15.5, 16.5, 15.5, 16.5, 15.5, 16.5, 15.5, 17.5, 15.5,
       16.5, 15.5, 15.5, 15.5, 16.5, 15.5, 15.5, 17.5, 15.5, 16.5, 15.5,
       16.5, 17.5, 17.5, 15.5, 15.5, 15.5, 16.5, 15.5, 17.5, 16.5, 15.5,
       15.5, 15.5, 17.5, 16.5, 17.5, 17.5, 15.5, 17.5, 15.5, 15.5, 16.5,
       17.5, 16.5, 17.5, 15.5, 15.5, 15.5, 16.5, 15.5, 17.5, 15.5, 17.5,
       15.5, 15.5, 16.5, 16.5, 16.5, 15.5, 16.5, 16

In [9]:
np.random.randint(120,200,500)

array([180, 146, 133, 197, 178, 145, 146, 174, 133, 163, 198, 147, 150,
       195, 183, 195, 150, 155, 127, 196, 144, 148, 148, 151, 169, 165,
       125, 165, 164, 129, 126, 170, 128, 185, 160, 121, 139, 190, 159,
       178, 131, 135, 182, 181, 192, 182, 164, 162, 122, 184, 142, 164,
       151, 188, 182, 187, 147, 156, 186, 192, 193, 149, 125, 162, 128,
       171, 161, 179, 179, 126, 183, 199, 192, 136, 139, 165, 165, 132,
       196, 121, 161, 160, 169, 130, 196, 191, 195, 139, 165, 143, 147,
       156, 173, 121, 162, 188, 127, 195, 158, 149, 128, 189, 141, 134,
       137, 175, 143, 125, 186, 158, 158, 185, 127, 167, 146, 181, 145,
       187, 191, 123, 148, 194, 192, 181, 166, 169, 180, 124, 138, 129,
       140, 160, 183, 153, 168, 143, 165, 130, 171, 172, 136, 154, 120,
       134, 194, 149, 189, 160, 169, 198, 123, 125, 144, 124, 173, 127,
       182, 142, 142, 194, 127, 133, 193, 155, 149, 130, 194, 135, 124,
       130, 125, 125, 164, 184, 177, 162, 174, 149, 175, 136, 19

In [31]:
np.random.seed(143)
arr=np.random.randint(20,99,(6,7))
arr

array([[98, 45, 37, 53, 54, 78, 67],
       [91, 49, 21, 41, 36, 75, 79],
       [30, 97, 32, 35, 82, 47, 65],
       [46, 53, 38, 38, 26, 90, 36],
       [57, 59, 80, 91, 37, 93, 46],
       [60, 87, 27, 78, 24, 35, 30]])

In [33]:
arr

array([[98, 45, 37, 53, 54, 78, 67],
       [91, 49, 21, 41, 36, 75, 79],
       [30, 97, 32, 35, 82, 47, 65],
       [46, 53, 38, 38, 26, 90, 36],
       [57, 59, 80, 91, 37, 93, 46],
       [60, 87, 27, 78, 24, 35, 30]])

In [35]:
arr.size

42

In [62]:
m=[2,4,6,8,9,10]
m

[2, 4, 6, 8, 9, 10]

In [70]:
for i in range(len(m)):
    m[i]=m[i]**2

In [72]:
[i**2 for i in m]

[16, 81, 1296, 625, 2401, 10000]

In [64]:
m[1] = 3
m[3] = 5
m[4] = 7

In [66]:
m

[2, 3, 6, 5, 7, 10]

In [74]:
b=(3,6,7,8,9)
b

(3, 6, 7, 8, 9)

In [96]:
b=(3,6,7,8,9)
b = tuple(x+5 for x in b)
b

(8, 11, 12, 13, 14)

In [98]:
k=[55,68,79,82,54,90,45]
k

[55, 68, 79, 82, 54, 90, 45]

In [100]:
for i in range(len(k)):
    k[i] >= 50

In [102]:
k

[55, 68, 79, 82, 54, 90, 45]

In [132]:
d=[]
for i in k:
    i<=50
    d.append(i)


In [136]:
d

[55, 68, 79, 82, 54, 90, 45]

In [124]:
np.random.seed(5)
arr=np.random.randint(20,90,10)
arr

array([81, 36, 28, 82, 47, 50, 27, 35, 73, 47])

In [142]:
arr**2

array([6561, 1296,  784, 6724, 2209, 2500,  729, 1225, 5329, 2209])

In [130]:
arr+5

array([86, 41, 33, 87, 52, 55, 32, 40, 78, 52])

In [144]:
k

[55, 68, 79, 82, 54, 90, 45]

In [148]:
arr-2

array([79, 34, 26, 80, 45, 48, 25, 33, 71, 45])

In [150]:
arr

array([81, 36, 28, 82, 47, 50, 27, 35, 73, 47])

In [152]:
arr/2

array([40.5, 18. , 14. , 41. , 23.5, 25. , 13.5, 17.5, 36.5, 23.5])

In [154]:
arr>50

array([ True, False, False,  True, False, False, False, False,  True,
       False])

In [156]:
arr[arr>50]

array([81, 82, 73])